version: '3'
services:
  web:
    container_name: web
    build: ./web
    networks:
      - webnet
    ports:
      - "4443:443"
      - "8080:80"
    environment:
      XDEBUG_CONFIG: "xdebug.remote_autostart=1 remote_host=host.docker.internal remote_log=/var/log/xdebug_remote.log"
    volumes:
      - ./app/src/public:/var/www/public_html

  db:
    container_name: db
    image: mysql:5.6
    env_file: ./db/db.env
    networks:
      - webnet
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/log.cnf:/etc/mysql/mysql.conf.d/log.cnf
      - ./logs:/var/log/mysql
    entrypoint: ""
    command: bash -c "chown -R mysql:mysql /var/log/mysql && exec /entrypoint.sh mysqld"

networks:
  webnet:

volumes:
    db_data: