version: '3'
services:
  web:
    container_name: web
    build: ./web
    networks:
      - webnet
    ports:
      - "4443:443"
      - "8080:80"
    environment:
      XDEBUG_CONFIG: "xdebug.remote_autostart=1 remote_host=host.docker.internal remote_log=/var/log/xdebug_remote.log"
    volumes:
      #非公開ソースをDocumentRootの一階層上に置くための共有フォルダ設定
      - ./app/src:/var/www
      #TODO:本来は上の共有設定だけにしたい。しかし、以下の問題があり暫定対処が必要。
      #ローカルのアプリのソースのフォルダ構成とコンテナのフォルダ構成に齟齬がある。
      #暫定対処として以下の共有フォルダ設定が必要。齟齬を解消しないと、冗長な設定とローカルのフォルダ構成がわかりづらくなる。
      - ./app/src/public:/var/www/public_html

  db:
    container_name: db
    image: mysql:5.6
    env_file: ./db/db.env
    networks:
      - webnet
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/log.cnf:/etc/mysql/mysql.conf.d/log.cnf
      - ./logs:/var/log/mysql
    entrypoint: ""
    command: bash -c "chown -R mysql:mysql /var/log/mysql && exec /entrypoint.sh mysqld"

networks:
  webnet:

volumes:
    db_data: